/**
 * New Order: Append-Only Event Logger
 *
 * Records all game actions, state changes, and events per turn. Provides
 * queryable access by turn, faction, event category, and compound filters.
 * Used for debugging, replay, post-game analysis, and the headline system.
 *
 * @see DR-106 — Event Log and Turn Replay Data
 *
 * @module engine/event-logger
 */

import type { EventLogEntry, EventLog } from '@/data/types/core.types';
import type {
  EventId,
  EventCategory,
  FactionId,
  TurnNumber,
} from '@/data/types/enums';
import { SeededRandom } from './rng';

// ─────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────

/**
 * Parameters for creating a new event log entry. The `id` and `timestamp`
 * fields are auto-generated by the logger.
 *
 * @see DR-106
 */
export type CreateEventParams = Omit<EventLogEntry, 'id' | 'timestamp'>;

/**
 * Compound filter for querying the event log. All specified fields must
 * match (logical AND). Unset fields are ignored.
 *
 * @see DR-106
 */
export interface EventFilter {
  /** Exact turn number to match. */
  readonly turn?: TurnNumber;
  /** Faction ID — matches events where the faction is source OR target. */
  readonly factionId?: FactionId;
  /** Event category to match. */
  readonly category?: EventCategory;
  /** Machine-readable action key to match. */
  readonly actionKey?: string;
  /** Inclusive turn range filter. */
  readonly turnRange?: {
    readonly min: TurnNumber;
    readonly max: TurnNumber;
  };
}

// ─────────────────────────────────────────────────────────
// EventLogger
// ─────────────────────────────────────────────────────────

/**
 * Append-only event logger for the simulation engine.
 *
 * Records every game event with an auto-generated unique ID and ISO-8601
 * timestamp. Supports deterministic ID generation when constructed with a
 * {@link SeededRandom} instance, ensuring replay-safe identifiers.
 *
 * ### Usage
 * ```ts
 * const logger = new EventLogger(rng);
 * logger.logEvent({ turn: 1 as TurnNumber, category: EventCategory.Military, ... });
 * const events = logger.getByTurn(1 as TurnNumber);
 * ```
 *
 * @see DR-106 — Event Log and Turn Replay Data
 */
export class EventLogger {
  /** Internal append-only event storage. */
  private entries: EventLogEntry[] = [];

  /** Optional seeded RNG for deterministic ID generation. */
  private readonly rng: SeededRandom | undefined;

  /** Monotonic counter for fallback (non-RNG) ID generation. */
  private counter = 0;

  /**
   * Create a new event logger.
   *
   * @param rng - Optional seeded PRNG for deterministic ID generation.
   *   When provided, IDs are derived from the RNG sequence, ensuring
   *   identical IDs across identical replay runs. When omitted, IDs
   *   use a timestamp + counter fallback.
   *
   * @see DR-106
   */
  constructor(rng?: SeededRandom) {
    this.rng = rng;
  }

  // ── Core methods ─────────────────────────────────────

  /**
   * Create and append a new event to the log.
   *
   * The `id` is auto-generated (deterministically if an RNG was provided)
   * and the `timestamp` is set to the current wall-clock time.
   *
   * @param params - All event fields except `id` and `timestamp`.
   * @returns The fully-constructed, appended event entry.
   *
   * @see DR-106
   */
  logEvent(params: CreateEventParams): EventLogEntry {
    const entry: EventLogEntry = {
      ...params,
      id: this.generateId(),
      timestamp: new Date().toISOString(),
    };
    this.entries.push(entry);
    return entry;
  }

  /**
   * Convenience method for logging system/environment events.
   *
   * Creates an event with `sourceFaction: null`, empty `targetFactions`,
   * and `category: 'Domestic'`.
   *
   * @param turn - The turn number.
   * @param description - Human-readable summary.
   * @param actionKey - Machine-readable action key.
   * @param payload - Optional arbitrary payload data.
   * @returns The fully-constructed, appended event entry.
   *
   * @see DR-106
   */
  logSystemEvent(
    turn: TurnNumber,
    description: string,
    actionKey: string,
    payload: Record<string, unknown> = {},
  ): EventLogEntry {
    return this.logEvent({
      turn,
      category: 'Domestic' as EventCategory,
      sourceFaction: null,
      targetFactions: [],
      description,
      actionKey,
      payload,
    });
  }

  // ── Query methods ────────────────────────────────────

  /**
   * Return all logged events.
   *
   * @returns A readonly view of the full event log.
   *
   * @see DR-106
   */
  getAll(): readonly EventLogEntry[] {
    return this.entries;
  }

  /**
   * Return all events for a specific turn.
   *
   * @param turn - The turn number to filter by.
   * @returns Matching events as a readonly array.
   *
   * @see DR-106
   */
  getByTurn(turn: TurnNumber): readonly EventLogEntry[] {
    return this.entries.filter((e) => e.turn === turn);
  }

  /**
   * Return all events involving a specific faction, either as
   * source or target.
   *
   * @param factionId - The faction ID to match.
   * @returns Matching events as a readonly array.
   *
   * @see DR-106
   */
  getByFaction(factionId: FactionId): readonly EventLogEntry[] {
    return this.entries.filter(
      (e) =>
        e.sourceFaction === factionId ||
        e.targetFactions.includes(factionId),
    );
  }

  /**
   * Return all events of a specific category.
   *
   * @param category - The event category to filter by.
   * @returns Matching events as a readonly array.
   *
   * @see DR-106
   */
  getByCategory(category: EventCategory): readonly EventLogEntry[] {
    return this.entries.filter((e) => e.category === category);
  }

  /**
   * Return all events with a specific action key.
   *
   * @param actionKey - The machine-readable action key to filter by.
   * @returns Matching events as a readonly array.
   *
   * @see DR-106
   */
  getByActionKey(actionKey: string): readonly EventLogEntry[] {
    return this.entries.filter((e) => e.actionKey === actionKey);
  }

  /**
   * Query the event log with a compound filter. All specified fields must
   * match (logical AND). Unset fields are ignored.
   *
   * @param filter - The compound filter to apply.
   * @returns Matching events as a readonly array.
   *
   * @see DR-106
   */
  query(filter: EventFilter): readonly EventLogEntry[] {
    return this.entries.filter((e) => {
      if (filter.turn !== undefined && e.turn !== filter.turn) {
        return false;
      }
      if (filter.category !== undefined && e.category !== filter.category) {
        return false;
      }
      if (filter.actionKey !== undefined && e.actionKey !== filter.actionKey) {
        return false;
      }
      if (filter.factionId !== undefined) {
        const matchesFaction =
          e.sourceFaction === filter.factionId ||
          e.targetFactions.includes(filter.factionId);
        if (!matchesFaction) {
          return false;
        }
      }
      if (filter.turnRange !== undefined) {
        if (e.turn < filter.turnRange.min || e.turn > filter.turnRange.max) {
          return false;
        }
      }
      return true;
    });
  }

  // ── State management ─────────────────────────────────

  /**
   * Return a deep copy of the full event log for serialisation.
   *
   * Mutations to the returned array do **not** affect the logger's
   * internal state.
   *
   * @returns A copy of all event entries.
   *
   * @see DR-106
   */
  getSnapshot(): EventLog {
    return this.entries.map((e) => ({ ...e }));
  }

  /**
   * Replace the internal event log with the provided entries.
   * Used when loading a saved game state.
   *
   * @param entries - The event log to restore.
   *
   * @see DR-106
   */
  restore(entries: EventLog): void {
    this.entries = entries.map((e) => ({ ...e }));
  }

  /**
   * Remove all entries from the log.
   *
   * @see DR-106
   */
  clear(): void {
    this.entries = [];
  }

  /**
   * The number of events currently in the log.
   *
   * @see DR-106
   */
  get count(): number {
    return this.entries.length;
  }

  // ── Private helpers ──────────────────────────────────

  /**
   * Generate a unique event ID.
   *
   * - With RNG: `evt-<6-char hex from RNG>` — deterministic across replays.
   * - Without RNG: `evt-<base36 timestamp>-<counter>` — unique but non-deterministic.
   */
  private generateId(): EventId {
    if (this.rng) {
      const hex = this.rng
        .nextInt(0, 0xffffff)
        .toString(16)
        .padStart(6, '0');
      return `evt-${hex}` as EventId;
    }
    const id = `evt-${Date.now().toString(36)}-${this.counter}`;
    this.counter++;
    return id as EventId;
  }
}
