/**
 * New Order: Personality Drift Engine
 *
 * Implements the personality-drift subsystem defined by FR-1505, FR-1506, and
 * FR-1507.  Leaders are not static — accumulated experience reshapes their
 * psychological profiles over time.  Prolonged stress shifts risk tolerance,
 * catastrophic events leave lasting trauma, betrayals fuel paranoia, and
 * victories inflate confidence.  After enough turns under extreme pressure a
 * leader can become *stress-inoculated*, gaining resilience at the cost of
 * ideological flexibility.
 *
 * All public methods are **pure functions**: they accept immutable inputs and
 * return new objects without mutating anything.  Config-driven thresholds and
 * multipliers are pulled from `GAME_CONFIG.psychology` so that balance tuning
 * requires no code changes (NFR-204).
 *
 * @module personality-drift
 * @see FR-1505 — Personality drift from accumulated experience
 * @see FR-1506 — Trauma response from catastrophic events
 * @see FR-1507 — Stress inoculation after prolonged high-stress exposure
 * @see NFR-204 — Config-driven formula tuning
 */

import type { LeaderId, TurnNumber, DriftEvent, LeaderPsychology } from '@/data/types';
import { TraumaType } from '@/data/types';
import { GAME_CONFIG } from './config';

// ─────────────────────────────────────────────────────────────────────────────
// Derived config type
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Shape of `GAME_CONFIG.psychology` extracted at the type level so that
 * consuming code can accept an arbitrary psychology configuration without
 * importing the full game config object.
 *
 * @see NFR-204
 */
export type PersonalityDriftConfig = typeof GAME_CONFIG.psychology;

// ─────────────────────────────────────────────────────────────────────────────
// Domain interfaces — Stress Drift
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Input for computing personality drift from prolonged high stress.
 *
 * @see FR-1505
 */
export interface StressDriftInput {
  /** The leader being evaluated. */
  readonly leaderId: LeaderId;
  /** How many consecutive turns the leader has been above the stress threshold. */
  readonly consecutiveHighStressTurns: number;
  /** The leader's current stress level (0–100). */
  readonly currentStress: number;
  /** The leader's innate stress response style. */
  readonly stressResponse: 'escalate' | 'consolidate' | 'retreat' | 'lash_out';
  /** The leader's current risk-tolerance value (0–100). */
  readonly currentRiskTolerance: number;
  /** Current game turn. */
  readonly currentTurn: TurnNumber;
}

/**
 * Result of stress-drift computation.
 *
 * @see FR-1505
 */
export interface StressDriftResult {
  /** Whether drift was triggered this evaluation. */
  readonly drifted: boolean;
  /** New risk-tolerance value after applying drift (clamped 0–100). */
  readonly newRiskTolerance: number;
  /** Signed delta applied to risk tolerance. */
  readonly delta: number;
  /** The drift event produced, or `null` if no drift occurred. */
  readonly driftEvent: DriftEvent | null;
  /** Human-readable explanation. */
  readonly reason: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Domain interfaces — Trauma Response
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Input for computing the psychological impact of a catastrophic event.
 *
 * @see FR-1506
 */
export interface TraumaInput {
  /** The leader experiencing the trauma. */
  readonly leaderId: LeaderId;
  /** The type of catastrophic event. */
  readonly traumaType: TraumaType;
  /** Current game turn. */
  readonly currentTurn: TurnNumber;
}

/**
 * Result of trauma-response computation.
 *
 * @see FR-1506
 */
export interface TraumaResult {
  /** The trauma type that was processed. */
  readonly traumaType: TraumaType;
  /** Emotional dimension effects (positive = increase). */
  readonly emotionalEffects: {
    readonly fear?: number;
    readonly paranoia?: number;
    readonly stress?: number;
    readonly confidence?: number;
    readonly anger?: number;
    readonly resolve?: number;
  };
  /** Power-base adjustments. */
  readonly powerBaseEffects: {
    readonly securityServices?: number;
    readonly public?: number;
  };
  /** Fatigue accumulation multiplier (1 = normal). */
  readonly fatigueMultiplier: number;
  /** How many turns the fatigue multiplier persists. */
  readonly fatigueMultiplierDuration: number;
  /** Override to the leader's stress response, or `null` if unchanged. */
  readonly stressResponseOverride: 'escalate' | 'retreat' | null;
  /** Drift events generated by this trauma. */
  readonly driftEvents: readonly DriftEvent[];
  /** Human-readable explanation. */
  readonly reason: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Domain interfaces — Betrayal Drift
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Input for computing paranoia drift after an ally's betrayal.
 *
 * @see FR-1505
 */
export interface BetrayalDriftInput {
  /** The leader who was betrayed. */
  readonly leaderId: LeaderId;
  /** The leader's current paranoia level (0–100). */
  readonly currentParanoia: number;
  /** Current game turn. */
  readonly currentTurn: TurnNumber;
}

/**
 * Result of betrayal-drift computation.
 *
 * @see FR-1505
 */
export interface BetrayalDriftResult {
  /** New paranoia value after drift (clamped 0–100). */
  readonly newParanoia: number;
  /** Signed delta applied to paranoia. */
  readonly delta: number;
  /** The drift event produced. */
  readonly driftEvent: DriftEvent;
  /** Human-readable explanation. */
  readonly reason: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Domain interfaces — Victory Drift
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Input for computing psychological drift after a major victory.
 *
 * @see FR-1505
 */
export interface VictoryDriftInput {
  /** The victorious leader. */
  readonly leaderId: LeaderId;
  /** Current confidence level (0–100). */
  readonly currentConfidence: number;
  /** Current narcissism level (0–100). */
  readonly currentNarcissism: number;
  /** Current game turn. */
  readonly currentTurn: TurnNumber;
}

/**
 * Result of victory-drift computation.
 *
 * @see FR-1505
 */
export interface VictoryDriftResult {
  /** New confidence value after drift (clamped 0–100). */
  readonly newConfidence: number;
  /** New narcissism value after drift (clamped 0–100). */
  readonly newNarcissism: number;
  /** Signed delta applied to confidence. */
  readonly confidenceDelta: number;
  /** Signed delta applied to narcissism. */
  readonly narcissismDelta: number;
  /** Drift events produced. */
  readonly driftEvents: readonly DriftEvent[];
  /** Human-readable explanation. */
  readonly reason: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Domain interfaces — Near-Loss Drift
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Input for computing psychological drift from a near-loss recovery.
 *
 * A "near loss" occurs when a leader's stability dropped below a critical
 * threshold but has since recovered above it.
 *
 * @see FR-1505
 */
export interface NearLossDriftInput {
  /** The leader who narrowly avoided collapse. */
  readonly leaderId: LeaderId;
  /** Current resolve level (0–100). */
  readonly currentResolve: number;
  /** Current pragmatism level (0–100). */
  readonly currentPragmatism: number;
  /** The lowest stability value the leader has experienced. */
  readonly lowestStability: number;
  /** The leader's current stability value. */
  readonly currentStability: number;
  /** Current game turn. */
  readonly currentTurn: TurnNumber;
}

/**
 * Result of near-loss drift computation.
 *
 * @see FR-1505
 */
export interface NearLossDriftResult {
  /** Whether the near-loss drift was triggered. */
  readonly triggered: boolean;
  /** New resolve value after drift (clamped 0–100). */
  readonly newResolve: number;
  /** New pragmatism value after drift (clamped 0–100). */
  readonly newPragmatism: number;
  /** Signed delta applied to resolve. */
  readonly resolveDelta: number;
  /** Signed delta applied to pragmatism. */
  readonly pragmatismDelta: number;
  /** Drift events produced. */
  readonly driftEvents: readonly DriftEvent[];
  /** Human-readable explanation. */
  readonly reason: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Domain interfaces — Stress Inoculation
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Input for computing stress inoculation status.
 *
 * After enough turns under extreme pressure a leader becomes
 * "stress-inoculated" — gaining resilience at the cost of ideological rigidity.
 *
 * @see FR-1507
 */
export interface InoculationInput {
  /** The leader being evaluated. */
  readonly leaderId: LeaderId;
  /** Total turns the leader has spent above the stress threshold. */
  readonly turnsAboveStressThreshold: number;
  /** Whether the leader is already inoculated. */
  readonly alreadyInoculated: boolean;
  /** Current pragmatism level (0–100). */
  readonly currentPragmatism: number;
  /** Current game turn. */
  readonly currentTurn: TurnNumber;
}

/**
 * Result of stress-inoculation computation.
 *
 * @see FR-1507
 */
export interface InoculationResult {
  /** Whether the leader is inoculated (either already or newly). */
  readonly inoculated: boolean;
  /** Whether inoculation was *just* triggered this evaluation. */
  readonly newlyInoculated: boolean;
  /** Modifier applied to all incoming stress gains (e.g. -0.2 = 20 % reduction). */
  readonly stressGainModifier: number;
  /** Signed delta applied to pragmatism. */
  readonly pragmatismDelta: number;
  /** Signed delta applied to ideology. */
  readonly ideologyDelta: number;
  /** Drift events produced. */
  readonly driftEvents: readonly DriftEvent[];
  /** Human-readable explanation. */
  readonly reason: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Engine class
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Pure-function engine for computing personality drift, trauma response, and
 * stress inoculation.
 *
 * All methods are deterministic and side-effect-free.  They consume immutable
 * inputs and produce new result objects.  Random elements (e.g. nuclear strike
 * escalate-vs-retreat) are intentionally *not* resolved here — callers must
 * roll their own RNG and use the probability fields on the result.
 *
 * @see FR-1505 — Personality drift from accumulated experience
 * @see FR-1506 — Trauma response from catastrophic events
 * @see FR-1507 — Stress inoculation after prolonged high-stress exposure
 */
export class PersonalityDriftEngine {
  private readonly cfg: PersonalityDriftConfig;

  constructor(config: PersonalityDriftConfig = GAME_CONFIG.psychology) {
    this.cfg = config;
  }

  // ───────────────────────────────────────────────────────────────────────────
  // Stress Drift
  // ───────────────────────────────────────────────────────────────────────────

  /**
   * Compute personality drift from prolonged high stress.
   *
   * If the leader has been above the stress threshold for enough consecutive
   * turns, their risk tolerance shifts: escalators and lash-out types become
   * *more* risk-tolerant, while consolidators and retreaters become *less*
   * risk-tolerant.
   *
   * @param input — Current stress-drift context.
   * @returns The drift result including any produced {@link DriftEvent}.
   * @see FR-1505
   */
  computeStressDrift(input: StressDriftInput): StressDriftResult {
    const pd = this.cfg.personalityDrift;

    const meetsConsecutiveTurns =
      input.consecutiveHighStressTurns >= pd.stressDriftTurns;
    const meetsStressThreshold =
      input.currentStress >= pd.stressDriftThreshold;

    if (!meetsConsecutiveTurns || !meetsStressThreshold) {
      return {
        drifted: false,
        newRiskTolerance: input.currentRiskTolerance,
        delta: 0,
        driftEvent: null,
        reason: !meetsConsecutiveTurns
          ? `Leader has ${input.consecutiveHighStressTurns}/${pd.stressDriftTurns} consecutive high-stress turns — drift not triggered`
          : `Current stress ${input.currentStress} below threshold ${pd.stressDriftThreshold} — drift not triggered`,
      };
    }

    const isAggressive =
      input.stressResponse === 'escalate' ||
      input.stressResponse === 'lash_out';
    const delta = isAggressive
      ? pd.riskToleranceShift
      : -pd.riskToleranceShift;
    const newRiskTolerance = PersonalityDriftEngine.clamp(
      input.currentRiskTolerance + delta,
      0,
      100,
    );

    const driftEvent: DriftEvent = {
      trigger: `stress_drift_${input.stressResponse}`,
      eventId: null,
      turn: input.currentTurn,
      dimension: 'riskTolerance' as keyof LeaderPsychology,
      delta,
    };

    return {
      drifted: true,
      newRiskTolerance,
      delta,
      driftEvent,
      reason: `${input.consecutiveHighStressTurns} consecutive high-stress turns with stress ${input.currentStress} — ` +
        `${isAggressive ? 'aggressive' : 'defensive'} response shifts risk tolerance by ${delta > 0 ? '+' : ''}${delta} to ${newRiskTolerance}`,
    };
  }

  // ───────────────────────────────────────────────────────────────────────────
  // Trauma Response
  // ───────────────────────────────────────────────────────────────────────────

  /**
   * Compute the psychological impact of a catastrophic event.
   *
   * Uses an exhaustive switch on {@link TraumaType} to ensure every trauma
   * variant is handled.  Each variant produces different emotional effects,
   * power-base adjustments, and potential stress-response overrides.
   *
   * @param input — The trauma context.
   * @returns A full {@link TraumaResult} describing all psychological impacts.
   * @see FR-1506
   */
  computeTraumaResponse(input: TraumaInput): TraumaResult {
    const tr = this.cfg.traumaResponse;

    switch (input.traumaType) {
      case TraumaType.NuclearStrike: {
        const cfg = tr.nuclearStrike;
        const driftEvents: DriftEvent[] = [
          {
            trigger: 'trauma_nuclear_strike_fear',
            eventId: null,
            turn: input.currentTurn,
            dimension: 'riskTolerance' as keyof LeaderPsychology,
            delta: -cfg.fearPermanentMin,
          },
        ];
        return {
          traumaType: input.traumaType,
          emotionalEffects: {
            fear: cfg.fearPermanentMin,
          },
          powerBaseEffects: {},
          fatigueMultiplier: 1,
          fatigueMultiplierDuration: 0,
          stressResponseOverride:
            cfg.escalateChance >= cfg.retreatChance ? 'escalate' : 'retreat',
          driftEvents,
          reason: `Nuclear strike trauma — fear floor set to ${cfg.fearPermanentMin}, ` +
            `${cfg.escalateChance * 100}% chance of escalation vs ${cfg.retreatChance * 100}% retreat`,
        };
      }

      case TraumaType.AssassinationAttempt: {
        const cfg = tr.assassinationAttempt;
        const driftEvents: DriftEvent[] = [
          {
            trigger: 'trauma_assassination_paranoia',
            eventId: null,
            turn: input.currentTurn,
            dimension: 'paranoia' as keyof LeaderPsychology,
            delta: cfg.paranoiaBoost,
          },
        ];
        return {
          traumaType: input.traumaType,
          emotionalEffects: {
            paranoia: cfg.paranoiaBoost,
          },
          powerBaseEffects: {
            securityServices: cfg.securityPowerBaseBoost,
            public: cfg.publicPowerBasePenalty,
          },
          fatigueMultiplier: 1,
          fatigueMultiplierDuration: 0,
          stressResponseOverride: null,
          driftEvents,
          reason: `Assassination attempt — paranoia +${cfg.paranoiaBoost}, ` +
            `security services power +${cfg.securityPowerBaseBoost}, ` +
            `public support ${cfg.publicPowerBasePenalty}`,
        };
      }

      case TraumaType.CapitalSiege: {
        const cfg = tr.capitalSiege;
        const driftEvents: DriftEvent[] = [
          {
            trigger: 'trauma_capital_siege_stress',
            eventId: null,
            turn: input.currentTurn,
            dimension: 'patience' as keyof LeaderPsychology,
            delta: -cfg.emotionalSpikeTo,
          },
        ];
        return {
          traumaType: input.traumaType,
          emotionalEffects: {
            stress: cfg.emotionalSpikeTo,
            fear: cfg.emotionalSpikeTo,
            anger: cfg.emotionalSpikeTo,
            confidence: -cfg.emotionalSpikeTo,
            resolve: cfg.emotionalSpikeTo,
          },
          powerBaseEffects: {},
          fatigueMultiplier: cfg.fatigueMultiplier,
          fatigueMultiplierDuration: cfg.fatigueMultiplierDuration,
          stressResponseOverride: null,
          driftEvents,
          reason: `Capital siege — all emotions spike to ${cfg.emotionalSpikeTo}, ` +
            `fatigue ${cfg.fatigueMultiplier}x for ${cfg.fatigueMultiplierDuration} turns`,
        };
      }

      default: {
        // Exhaustive check — TypeScript will error if a TraumaType variant is unhandled.
        const _exhaustive: never = input.traumaType;
        throw new Error(`Unhandled trauma type: ${_exhaustive as string}`);
      }
    }
  }

  // ───────────────────────────────────────────────────────────────────────────
  // Betrayal Drift
  // ───────────────────────────────────────────────────────────────────────────

  /**
   * Compute paranoia drift after an ally's betrayal.
   *
   * Betrayal always increases paranoia by the configured amount, clamped to
   * the 0–100 range.
   *
   * @param input — Betrayal context.
   * @returns The drift result.
   * @see FR-1505
   */
  computeBetrayalDrift(input: BetrayalDriftInput): BetrayalDriftResult {
    const delta = this.cfg.personalityDrift.betrayalParanoiaIncrease;
    const newParanoia = PersonalityDriftEngine.clamp(
      input.currentParanoia + delta,
      0,
      100,
    );

    const driftEvent: DriftEvent = {
      trigger: 'betrayal_paranoia_drift',
      eventId: null,
      turn: input.currentTurn,
      dimension: 'paranoia' as keyof LeaderPsychology,
      delta,
    };

    return {
      newParanoia,
      delta,
      driftEvent,
      reason: `Ally betrayal — paranoia +${delta} (${input.currentParanoia} → ${newParanoia})`,
    };
  }

  // ───────────────────────────────────────────────────────────────────────────
  // Victory Drift
  // ───────────────────────────────────────────────────────────────────────────

  /**
   * Compute psychological drift from a major victory.
   *
   * Victories boost both confidence and narcissism, reflecting the leader's
   * growing self-assurance and sense of personal destiny.
   *
   * @param input — Victory context.
   * @returns The drift result.
   * @see FR-1505
   */
  computeVictoryDrift(input: VictoryDriftInput): VictoryDriftResult {
    const pd = this.cfg.personalityDrift;
    const confidenceDelta = pd.victoryConfidenceBoost;
    const narcissismDelta = pd.victoryNarcissismBoost;

    const newConfidence = PersonalityDriftEngine.clamp(
      input.currentConfidence + confidenceDelta,
      0,
      100,
    );
    const newNarcissism = PersonalityDriftEngine.clamp(
      input.currentNarcissism + narcissismDelta,
      0,
      100,
    );

    const driftEvents: readonly DriftEvent[] = [
      {
        trigger: 'victory_confidence_drift',
        eventId: null,
        turn: input.currentTurn,
        dimension: 'narcissism' as keyof LeaderPsychology,
        delta: confidenceDelta,
      },
      {
        trigger: 'victory_narcissism_drift',
        eventId: null,
        turn: input.currentTurn,
        dimension: 'narcissism' as keyof LeaderPsychology,
        delta: narcissismDelta,
      },
    ];

    return {
      newConfidence,
      newNarcissism,
      confidenceDelta,
      narcissismDelta,
      driftEvents,
      reason: `Major victory — confidence +${confidenceDelta} (→ ${newConfidence}), ` +
        `narcissism +${narcissismDelta} (→ ${newNarcissism})`,
    };
  }

  // ───────────────────────────────────────────────────────────────────────────
  // Near-Loss Drift
  // ───────────────────────────────────────────────────────────────────────────

  /**
   * Compute psychological drift from a near-loss recovery.
   *
   * Only triggers if the leader's stability once fell below the critical
   * threshold but has since recovered above it.  The experience of almost
   * losing everything hardens resolve and increases pragmatism.
   *
   * @param input — Near-loss context.
   * @returns The drift result.
   * @see FR-1505
   */
  computeNearLossDrift(input: NearLossDriftInput): NearLossDriftResult {
    const pd = this.cfg.personalityDrift;

    const droppedBelowThreshold =
      input.lowestStability < pd.nearLossStabilityThreshold;
    const recoveredAboveThreshold =
      input.currentStability >= pd.nearLossStabilityThreshold;

    if (!droppedBelowThreshold || !recoveredAboveThreshold) {
      return {
        triggered: false,
        newResolve: input.currentResolve,
        newPragmatism: input.currentPragmatism,
        resolveDelta: 0,
        pragmatismDelta: 0,
        driftEvents: [],
        reason: !droppedBelowThreshold
          ? `Lowest stability ${input.lowestStability} never fell below threshold ${pd.nearLossStabilityThreshold} — no near-loss drift`
          : `Current stability ${input.currentStability} still below threshold ${pd.nearLossStabilityThreshold} — recovery not yet complete`,
      };
    }

    const resolveDelta = pd.nearLossResolveBoost;
    const pragmatismDelta = pd.nearLossPragmatismBoost;

    const newResolve = PersonalityDriftEngine.clamp(
      input.currentResolve + resolveDelta,
      0,
      100,
    );
    const newPragmatism = PersonalityDriftEngine.clamp(
      input.currentPragmatism + pragmatismDelta,
      0,
      100,
    );

    const driftEvents: readonly DriftEvent[] = [
      {
        trigger: 'near_loss_resolve_drift',
        eventId: null,
        turn: input.currentTurn,
        dimension: 'vengefulIndex' as keyof LeaderPsychology,
        delta: resolveDelta,
      },
      {
        trigger: 'near_loss_pragmatism_drift',
        eventId: null,
        turn: input.currentTurn,
        dimension: 'pragmatism' as keyof LeaderPsychology,
        delta: pragmatismDelta,
      },
    ];

    return {
      triggered: true,
      newResolve,
      newPragmatism,
      resolveDelta,
      pragmatismDelta,
      driftEvents,
      reason: `Near-loss recovery (stability ${input.lowestStability} → ${input.currentStability}) — ` +
        `resolve +${resolveDelta} (→ ${newResolve}), pragmatism +${pragmatismDelta} (→ ${newPragmatism})`,
    };
  }

  // ───────────────────────────────────────────────────────────────────────────
  // Stress Inoculation
  // ───────────────────────────────────────────────────────────────────────────

  /**
   * Compute stress inoculation status.
   *
   * After enough cumulative turns above the stress threshold a leader becomes
   * "stress-inoculated" — they gain a permanent reduction to incoming stress
   * gains and a pragmatism boost, at the cost of reduced ideological conviction.
   *
   * If the leader is already inoculated the method returns the ongoing modifier
   * without generating new drift events.
   *
   * @param input — Inoculation context.
   * @returns The inoculation result.
   * @see FR-1507
   */
  computeStressInoculation(input: InoculationInput): InoculationResult {
    const si = this.cfg.stressInoculation;

    // Already inoculated — return ongoing benefits, no new events.
    if (input.alreadyInoculated) {
      return {
        inoculated: true,
        newlyInoculated: false,
        stressGainModifier: si.stressGainReduction,
        pragmatismDelta: 0,
        ideologyDelta: 0,
        driftEvents: [],
        reason: 'Leader is already stress-inoculated — ongoing stress reduction active',
      };
    }

    // Not yet eligible.
    if (input.turnsAboveStressThreshold < si.turnsRequired) {
      return {
        inoculated: false,
        newlyInoculated: false,
        stressGainModifier: 0,
        pragmatismDelta: 0,
        ideologyDelta: 0,
        driftEvents: [],
        reason: `${input.turnsAboveStressThreshold}/${si.turnsRequired} turns above stress threshold ${si.stressThreshold} — inoculation not yet triggered`,
      };
    }

    // Newly inoculated this evaluation.
    const driftEvents: readonly DriftEvent[] = [
      {
        trigger: 'stress_inoculation_pragmatism',
        eventId: null,
        turn: input.currentTurn,
        dimension: 'pragmatism' as keyof LeaderPsychology,
        delta: si.pragmatismBoost,
      },
      {
        trigger: 'stress_inoculation_ideology',
        eventId: null,
        turn: input.currentTurn,
        dimension: 'patience' as keyof LeaderPsychology,
        delta: si.ideologyReduction,
      },
    ];

    return {
      inoculated: true,
      newlyInoculated: true,
      stressGainModifier: si.stressGainReduction,
      pragmatismDelta: si.pragmatismBoost,
      ideologyDelta: si.ideologyReduction,
      driftEvents,
      reason: `Stress inoculation triggered after ${input.turnsAboveStressThreshold} turns — ` +
        `stress gain modifier ${si.stressGainReduction}, pragmatism +${si.pragmatismBoost}, ideology ${si.ideologyReduction}`,
    };
  }

  // ───────────────────────────────────────────────────────────────────────────
  // Private helpers
  // ───────────────────────────────────────────────────────────────────────────

  /**
   * Clamp a numeric value to the `[min, max]` range.
   */
  private static clamp(value: number, min: number, max: number): number {
    return Math.max(min, Math.min(max, value));
  }
}
